[declared]
AddAssoc = ["traits", "additive"]
AddComm = ["traits", "additive"]
AssocVal = ["traits", "assoc_val"]
Associative = ["traits", "binop"]
Commutative = ["traits", "binop"]
CommutativeGroup = ["traits", "binop"]
CommutativeMonoid = ["traits", "binop"]
CommutativeRing = ["traits", "binop"]
DisjointSet = ["traits", "disjoint_set"]
DisjointSparseTable = ["ds", "disjoint_sparse_table"]
Distributive = ["traits", "binop"]
ElasticSlice = ["traits", "elastic_slice"]
EndBounded = ["traits", "range_bounds"]
EndExclusive = ["traits", "range_bounds"]
EndInclusive = ["traits", "range_bounds"]
EndUnbounded = ["traits", "range_bounds"]
ExpandBack = ["traits", "elastic_slice"]
ExpandFront = ["traits", "elastic_slice"]
Field = ["traits", "binop"]
Fold = ["traits", "fold"]
FoldBisect = ["traits", "fold_bisect"]
FoldBisectRev = ["traits", "fold_bisect"]
FoldableDeque = ["ds", "foldable_deque"]
FoldableQueue = ["ds", "foldable_queue"]
GetMut = ["traits", "get_mut"]
GetMutIndex = ["ds", "vec_segtree"]
Group = ["traits", "binop"]
Identity = ["traits", "binop"]
Magma = ["traits", "binop"]
Max = ["traits", "max"]
Min = ["traits", "min"]
ModInt = ["math", "modint"]
Monoid = ["traits", "binop"]
MulAssoc = ["traits", "multiplicative"]
MulComm = ["traits", "multiplicative"]
MulRecip = ["traits", "multiplicative"]
One = ["traits", "multiplicative"]
OpAdd = ["utils", "op_add"]
OpMax = ["utils", "op_max"]
OpMin = ["utils", "op_min"]
OpMul = ["utils", "op_mul"]
OpRollHash = ["utils", "op_roll_hash"]
PartialRecip = ["traits", "binop"]
Pop = ["traits", "push_pop"]
PopBack = ["traits", "push_pop"]
PopFront = ["traits", "push_pop"]
Push = ["traits", "push_pop"]
PushBack = ["traits", "push_pop"]
PushFront = ["traits", "push_pop"]
Recip = ["traits", "binop"]
Ring = ["traits", "binop"]
Scan = ["utils", "scanner"]
ScanTupleError = ["utils", "scanner"]
Scanner = ["utils", "scanner"]
Semigroup = ["traits", "binop"]
SetValue = ["traits", "set_value"]
ShrinkBack = ["traits", "elastic_slice"]
ShrinkFront = ["traits", "elastic_slice"]
SliceHash = ["traits", "elastic_slice"]
StartBounded = ["traits", "range_bounds"]
StartInclusive = ["traits", "range_bounds"]
StartUnbounded = ["traits", "range_bounds"]
StatefulPred = ["traits", "stateful_predicate"]
UnionFind = ["ds", "union_find"]
VecSegtree = ["ds", "vec_segtree"]
Zero = ["traits", "additive"]
bisect = ["algo", "bisect"]
bounds_within = ["utils", "buf_range"]
dijkstra = ["graph", "dijkstra"]
extremum = ["algo", "extremum"]
extremum_float = ["algo", "extremum_float"]
impl_assoc_val = ["traits", "assoc_val"]
impl_mod_int = ["math", "modint"]
mo = ["algo", "mo"]
parallel_bisect = ["algo", "parallel_bisect"]
tortoise_hare = ["algo", "tortoise_hare"]
window_bisect = ["algo", "window_bisect"]

[depends]
"algo::mo" = [["traits", "elastic_slice"]]
"algo::parallel_bisect" = [["traits", "stateful_predicate"]]
"algo::window_bisect" = [["traits", "elastic_slice"]]
"ds::disjoint_sparse_table" = [["traits", "binop"], ["utils", "buf_range"], ["traits", "fold"]]
"ds::foldable_deque" = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]
"ds::foldable_queue" = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]
"ds::union_find" = [["traits", "disjoint-set"]]
"ds::vec_segtree" = [["traits", "binop"], ["utils", "buf_range"], ["traits", "fold"], ["traits", "fold_bisect"], ["traits", "get_mut"], ["traits", "set_value"]]
"math::modint" = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "multiplicative"]]
"math::polynomial" = [["traits", "assoc_val"], ["math", "modint"]]
"traits::fold" = [["traits", "binop"]]
"traits::fold_bisect" = [["traits", "binop"], ["traits", "fold"]]
"utils::op_add" = [["traits", "additive"], ["traits", "binop"]]
"utils::op_max" = [["traits", "binop"], ["traits", "min"]]
"utils::op_min" = [["traits", "binop"], ["traits", "max"]]
"utils::op_mul" = [["traits", "binop"], ["traits", "multiplicative"], ["utils", "op_add"]]
"utils::op_roll_hash" = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "binop"], ["traits", "multiplicative"]]
