[declared]
Act = ["traits", "act"]
AddAssoc = ["traits", "additive"]
AddComm = ["traits", "additive"]
AssocVal = ["traits", "assoc_val"]
Associative = ["traits", "binop"]
BicrementalMedian = ["ds", "bicremental_median"]
BicrementalMedianDev = ["ds", "bicremental_median_dev"]
BitSet = ["ds", "bit_set"]
CarmichaelLambda = ["math", "carmichael_lambda"]
Commutative = ["traits", "binop"]
CommutativeGroup = ["traits", "binop"]
CommutativeMonoid = ["traits", "binop"]
CommutativeRing = ["traits", "binop"]
CompactSieve = ["math", "compact_sieve"]
ConstDiv = ["math", "const_div"]
ConstDiv2 = ["math", "const_div"]
Count = ["traits", "count"]
Count3way = ["traits", "count"]
CuckooHashMap = ["ds", "cuckoo_hash_map"]
CuckooHashSet = ["ds", "cuckoo_hash_set"]
DLog = ["math", "dlog"]
DigitSum = ["math", "digit_sum"]
DisjointSet = ["traits", "disjoint_set"]
DisjointSparseTable = ["ds", "disjoint_sparse_table"]
Distributive = ["traits", "binop"]
Divisors = ["math", "divisors"]
ElasticSlice = ["traits", "elastic_slice"]
EndBounded = ["traits", "range_bounds"]
EndExclusive = ["traits", "range_bounds"]
EndInclusive = ["traits", "range_bounds"]
EndUnbounded = ["traits", "range_bounds"]
EquivMod = ["math", "equiv_mod"]
EquivModIter = ["math", "equiv_mod"]
EulerPhi = ["math", "euler_phi"]
ExactCover = ["algo", "exact_cover"]
ExpandBack = ["traits", "elastic_slice"]
ExpandFront = ["traits", "elastic_slice"]
Factors = ["math", "factors"]
Field = ["traits", "binop"]
FindNth = ["traits", "find_nth"]
Fold = ["traits", "fold"]
FoldBisect = ["traits", "fold_bisect"]
FoldBisectRev = ["traits", "fold_bisect"]
FoldableDeque = ["ds", "foldable_deque"]
FoldableQueue = ["ds", "foldable_queue"]
Gcd = ["math", "gcd"]
GcdRecip = ["math", "gcd_recip"]
GetMut = ["traits", "get_mut"]
Group = ["traits", "binop"]
HarmonicFloorSum = ["math", "harmonic_floor_sum"]
Identity = ["traits", "binop"]
IncrementalLineSet = ["math", "incremental_line_set"]
Interpolation = ["math", "interpolation"]
IntervalSet = ["ds", "interval_set"]
KmpSearcher = ["seq", "kmp"]
Lcm = ["math", "lcm"]
LinearFloorSum = ["math", "linear_floor_sum"]
LinearSieve = ["math", "linear_sieve"]
Magma = ["traits", "binop"]
Max = ["traits", "max"]
Min = ["traits", "min"]
ModAckermann = ["math", "mod_ackermann"]
ModInt = ["math", "modint"]
ModOrd = ["math", "mod_ord"]
ModPow = ["math", "mod_pow"]
ModTetration = ["math", "mod_tetration"]
Monoid = ["traits", "binop"]
MonoidAction = ["traits", "action"]
MulAssoc = ["traits", "multiplicative"]
MulComm = ["traits", "multiplicative"]
MulRecip = ["traits", "multiplicative"]
One = ["traits", "multiplicative"]
OpAdd = ["utils", "op_add"]
OpMax = ["utils", "op_max"]
OpMin = ["utils", "op_min"]
OpMul = ["utils", "op_mul"]
OpRollHash = ["utils", "op_roll_hash"]
PartialRecip = ["traits", "binop"]
Pop = ["traits", "push_pop"]
PopBack = ["traits", "push_pop"]
PopFront = ["traits", "push_pop"]
Push = ["traits", "push_pop"]
PushBack = ["traits", "push_pop"]
PushFront = ["traits", "push_pop"]
Quantile = ["traits", "quantile"]
Recip = ["traits", "binop"]
RemovableHeap = ["ds", "removable_heap"]
Ring = ["traits", "binop"]
RsDict = ["ds", "rs_dict"]
Scanner = ["utils", "scanner"]
Semigroup = ["traits", "binop"]
SetValue = ["traits", "set_value"]
ShrinkBack = ["traits", "elastic_slice"]
ShrinkFront = ["traits", "elastic_slice"]
SieveN2Plus1 = ["math", "sieve_n2_plus_1"]
SieveN2PlusNPlus1 = ["math", "sieve_n2_plus_n_plus_1"]
SliceHash = ["traits", "elastic_slice"]
SlopeFunction = ["math", "slope_function"]
Sqrt = ["math", "sqrt"]
StartBounded = ["traits", "range_bounds"]
StartInclusive = ["traits", "range_bounds"]
StartUnbounded = ["traits", "range_bounds"]
StatefulPred = ["traits", "stateful_predicate"]
SuffixArray = ["seq", "suffix_array"]
Tree = ["graph", "tree"]
TwoSat = ["math", "two_sat"]
UnionFind = ["ds", "union_find"]
VecActSegtree = ["ds", "vec_act_segtree"]
VecSegtree = ["ds", "vec_segtree"]
WaveletMatrix = ["ds", "wavelet_matrix"]
ZSearcher = ["seq", "z_algo"]
Zero = ["traits", "additive"]
bisect = ["algo", "bisect"]
bisect_slice = ["algo", "bisect"]
bit_binom = ["math", "bit_binom_"]
bounds_within = ["utils", "buf_range"]
continued_fraction = ["math", "continued_fraction_"]
convolve = ["algo", "karatsuba"]
dijkstra = ["graph", "dijkstra_"]
dinic = ["graph", "dinic_"]
extremum = ["algo", "extremum"]
extremum_float = ["algo", "extremum_float"]
extremum_slice = ["algo", "extremum"]
majority = ["algo", "majority_"]
minmax = ["algo", "minmax"]
minmax_by = ["algo", "minmax"]
minmax_by_key = ["algo", "minmax"]
mo = ["algo", "mo"]
next_permutation = ["algo", "permutation"]
parallel_bisect = ["algo", "parallel_bisect"]
prime_pi = ["math", "count_prime"]
scc = ["graph", "scc_"]
sqrt_fraction = ["math", "sqrt_fraction_"]
sqrt_fraction_fn = ["math", "sqrt_fraction_"]
stern_brocot = ["math", "stern_brocot_"]
tortoise_hare = ["algo", "tortoise_hare"]
window_bisect = ["algo", "window_bisect"]

[[depends]]
name = ["algo", "mo"]
direct = [["traits", "elastic_slice"]]
whole = [["traits", "elastic_slice"]]

[[depends]]
name = ["algo", "parallel_bisect"]
direct = [["traits", "stateful_predicate"]]
whole = [["traits", "stateful_predicate"]]

[[depends]]
name = ["algo", "window_bisect"]
direct = [["traits", "elastic_slice"]]
whole = [["traits", "elastic_slice"]]

[[depends]]
name = ["ds", "bicremental_median_dev"]
direct = [["traits", "binop"]]
whole = [["traits", "binop"]]

[[depends]]
name = ["ds", "cuckoo_hash_set"]
direct = [["ds", "cuckoo_hash_map"]]
whole = [["ds", "cuckoo_hash_map"]]

[[depends]]
name = ["ds", "disjoint_sparse_table"]
direct = [["traits", "binop"], ["traits", "fold"], ["utils", "buf_range"]]
whole = [["traits", "binop"], ["traits", "fold"], ["utils", "buf_range"]]

[[depends]]
name = ["ds", "foldable_deque"]
direct = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]
whole = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]

[[depends]]
name = ["ds", "foldable_queue"]
direct = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]
whole = [["traits", "binop"], ["traits", "fold"], ["traits", "push_pop"]]

[[depends]]
name = ["ds", "potentialized_union_find"]
direct = [["traits", "binop"], ["traits", "potential_function"]]
whole = [["traits", "binop"], ["traits", "potential_function"]]

[[depends]]
name = ["ds", "rs_dict"]
direct = [["traits", "count"], ["traits", "find_nth"], ["utils", "buf_range"]]
whole = [["traits", "count"], ["traits", "find_nth"], ["utils", "buf_range"]]

[[depends]]
name = ["ds", "union_find"]
direct = [["traits", "disjoint_set"]]
whole = [["traits", "disjoint_set"]]

[[depends]]
name = ["ds", "vec_act_segtree"]
direct = [["traits", "act"], ["traits", "action"], ["traits", "binop"], ["traits", "fold"], ["traits", "fold_bisect"], ["utils", "buf_range"]]
whole = [["traits", "act"], ["traits", "action"], ["traits", "binop"], ["traits", "fold"], ["traits", "fold_bisect"], ["utils", "buf_range"]]

[[depends]]
name = ["ds", "vec_segtree"]
direct = [["traits", "binop"], ["traits", "fold"], ["traits", "fold_bisect"], ["traits", "get_mut"], ["traits", "set_value"], ["utils", "buf_range"]]
whole = [["traits", "binop"], ["traits", "fold"], ["traits", "fold_bisect"], ["traits", "get_mut"], ["traits", "set_value"], ["utils", "buf_range"]]

[[depends]]
name = ["ds", "wavelet_matrix"]
direct = [["ds", "rs_dict"], ["traits", "count"], ["traits", "find_nth"], ["traits", "quantile"], ["utils", "buf_range"]]
whole = [["ds", "rs_dict"], ["traits", "count"], ["traits", "find_nth"], ["traits", "quantile"], ["utils", "buf_range"]]

[[depends]]
name = ["math", "carmichael_lambda"]
direct = [["math", "factors"], ["math", "lcm"]]
whole = [["math", "factors"], ["math", "gcd"], ["math", "lcm"]]

[[depends]]
name = ["math", "crt"]
direct = [["math", "gcd_recip"]]
whole = [["math", "gcd_recip"]]

[[depends]]
name = ["math", "dlog"]
direct = [["math", "carmichael_lambda"], ["math", "divisors"], ["math", "factors"], ["math", "gcd"], ["math", "mod_pow"]]
whole = [["math", "carmichael_lambda"], ["math", "divisors"], ["math", "factors"], ["math", "gcd"], ["math", "lcm"], ["math", "mod_pow"]]

[[depends]]
name = ["math", "equiv_mod"]
direct = [["math", "gcd_recip"]]
whole = [["math", "gcd_recip"]]

[[depends]]
name = ["math", "euler_phi"]
direct = [["math", "factors"]]
whole = [["math", "factors"]]

[[depends]]
name = ["math", "interpolation"]
direct = [["math", "const_div"], ["math", "gcd_recip"]]
whole = [["math", "const_div"], ["math", "gcd_recip"]]

[[depends]]
name = ["math", "lcm"]
direct = [["math", "gcd"]]
whole = [["math", "gcd"]]

[[depends]]
name = ["math", "mod_ackermann"]
direct = [["math", "mod_pow"], ["math", "mod_tetration"]]
whole = [["math", "euler_phi"], ["math", "factors"], ["math", "mod_pow"], ["math", "mod_tetration"]]

[[depends]]
name = ["math", "mod_ord"]
direct = [["math", "carmichael_lambda"], ["math", "factors"], ["math", "gcd"], ["math", "mod_pow"]]
whole = [["math", "carmichael_lambda"], ["math", "factors"], ["math", "gcd"], ["math", "lcm"], ["math", "mod_pow"]]

[[depends]]
name = ["math", "mod_tetration"]
direct = [["math", "euler_phi"]]
whole = [["math", "euler_phi"], ["math", "factors"]]

[[depends]]
name = ["math", "modint"]
direct = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "multiplicative"]]
whole = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "multiplicative"]]

[[depends]]
name = ["math", "polynomial"]
direct = [["math", "modint"], ["traits", "assoc_val"]]
whole = [["math", "modint"], ["traits", "additive"], ["traits", "assoc_val"], ["traits", "multiplicative"]]

[[depends]]
name = ["math", "sqrt_fraction_"]
direct = [["math", "sqrt"]]
whole = [["math", "sqrt"]]

[[depends]]
name = ["math", "two_sat"]
direct = [["graph", "scc_"]]
whole = [["graph", "scc_"]]

[[depends]]
name = ["seq", "kmp"]
direct = [["traits", "push_pop"]]
whole = [["traits", "push_pop"]]

[[depends]]
name = ["traits", "act"]
direct = [["traits", "action"], ["traits", "binop"]]
whole = [["traits", "action"], ["traits", "binop"]]

[[depends]]
name = ["traits", "action"]
direct = [["traits", "binop"]]
whole = [["traits", "binop"]]

[[depends]]
name = ["traits", "fold"]
direct = [["traits", "binop"]]
whole = [["traits", "binop"]]

[[depends]]
name = ["traits", "fold_bisect"]
direct = [["traits", "binop"], ["traits", "fold"]]
whole = [["traits", "binop"], ["traits", "fold"]]

[[depends]]
name = ["traits", "potential_function"]
direct = [["traits", "binop"]]
whole = [["traits", "binop"]]

[[depends]]
name = ["utils", "op_add"]
direct = [["traits", "additive"], ["traits", "binop"]]
whole = [["traits", "additive"], ["traits", "binop"]]

[[depends]]
name = ["utils", "op_max"]
direct = [["traits", "binop"], ["traits", "min"]]
whole = [["traits", "binop"], ["traits", "min"]]

[[depends]]
name = ["utils", "op_min"]
direct = [["traits", "binop"], ["traits", "max"]]
whole = [["traits", "binop"], ["traits", "max"]]

[[depends]]
name = ["utils", "op_mul"]
direct = [["traits", "binop"], ["traits", "multiplicative"], ["utils", "op_add"]]
whole = [["traits", "additive"], ["traits", "binop"], ["traits", "multiplicative"], ["utils", "op_add"]]

[[depends]]
name = ["utils", "op_roll_hash"]
direct = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "binop"], ["traits", "multiplicative"]]
whole = [["traits", "additive"], ["traits", "assoc_val"], ["traits", "binop"], ["traits", "multiplicative"]]
