[workspace]
members = [
    'crates/algo/*/',
    'crates/ds/*/',
    'crates/graph/*/',
    'crates/math/*/',
    'crates/seq/*/',
    'crates/traits/*/',
    'crates/utils/*/',
    'verifiers/download',
    'verifiers/verify',
    'notes/',
]
