# See https://doc.rust-lang.org/cargo/reference/config.html

[alias]
d = "doc --no-deps"
p = "clippy -- -W clippy::pedantic -A clippy::doc_markdown -A clippy::module_name_repetitions"

[build]
rustdocflags = [
    "--html-in-header", "katex-header.html",
    "--html-in-header", "lato-header.html",
    "--html-in-header", "ferris-in-doc.html",
]
