[package]
name = "op_gcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binop = { path = "../../traits/binop" }
gcd = { path = "../../math/gcd" }
additive = { path = "../../traits/additive" }
