[package]
name = "bundler"
version = "0.1.0"
authors = ["rsk0315 <rsk0315@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.48", features = ["full", "extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.24"
toml = "0.5.7"
serde = { version = "1.0.117", features = ["derive"] }
