# See https://doc.rust-lang.org/cargo/reference/config.html

[alias]
d = "doc"
p = "clippy -- -W clippy::pedantic -A clippy::doc_markdown -A clippy::module_name_repetitions"

[build]
# Comment out next line when you run `cargo test`.
# rustdocflags = ["--html-in-header", "katex-header.html"]
