[package]
name = "prime_pi_"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bisect = { path = "../../traits/bisect" }
linear_sieve = { path = "../linear_sieve" }
