[package]
name = "incremental_line_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btree_bimap = { path = "../btree_bimap" }
