[package]
name = "op_closure_on_op_closure"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
op_closure = { path = "../op_closure" }
action = { path = "../../traits/action" }
