name: fail

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      status:
        type: choice
        options:
          - passing
          - failing

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: |
          if [[ ${{ github.event.inputs.status }} == passing ]]; then
              true
          else
              false
          fi
