name: fail

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      status:
        type: choice
        options:
          - passing
          - failing

jobs:
  perform:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: |
          status=${{ github.event.inputs.status }}
          if [[ "${status:-failing}" == passing ]]; then
              true
          else
              false
          fi
