name: generate mirror

on:
  push:
    branches:
      - master
    paths:
      - '.cargo/config.toml'
      - 'Cargo.toml'
      - 'static/**'
      - 'crates/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - uses: actions/checkout@v2
        with:
          ref: doc
          path: doc

      - name: Generate mirror
        run: |
          pwd
          [[ -d doc/gen/generated ]] && rm -Rf doc/gen/generated
          cp -R master/static doc/gen/generated
          cd doc
          [[ -d .trigger ]] || mkdir .trigger
          date --rfc-3339=seconds > .trigger/gen_doc
          echo ${GITHUB_SHA} >> .trigger/gen_doc
          cp .trigger/gen_doc .trigger/doc_test
          cd gen
          cargo run
          cd ..
          git add .
          ls *
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m '[auto-generated]' || true

      - name: Push
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: doc
          target-branch: doc
          destination-github-username: 'rsk0315'
          destination-repository-name: 'library-rs'
          user-email: 'github-actions@github.com'
