name: neko

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Precheck
        run: |
          echo $HOME
          pwd

      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - uses: actions/checkout@v2
        with:
          ref: doc
          path: doc

      - name: Postcheck
        run: |
          ls master doc
