name: neko

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Nya
      run: echo nya; echo test; echo nya > nya.txt

    - name: Check environments
      run: pwd; git status
