name: neko

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: doc

    - name: Nya
      run: |
        echo test
        git status
        echo nya > nya.txt
        git commit -m Nya nya.txt
        git push
