name: pr doctest

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # スクリプトが master/ を読むことになっている...
          path: master

      - uses: actions/checkout@v2
        with:
          ref: doc
          path: doc

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Generate mirror
        run: |
          pwd
          [[ -d doc/gen/generated ]] && rm -Rf doc/gen/generated
          cd master/script
          cargo run --bin revision-art ${GITHUB_SHA} >> ../static/nekolib/src/lib.rs
          cd ../..
          mkdir -p doc/gen
          cp -R master/static doc/gen/generated
          cd doc/gen
          ls
          cargo run --release

      - name: Test documents
        run: |
          pwd
          cd doc/gen/generated
          cargo d
          cd target/doc
          ls
          cd -
          cargo t --doc
