name: test --lib

on:
  push:
    branches:
      - master
    paths:
      - 'crates/**'
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test lib
        run: |
          cd crates
          cargo test --release --lib
