name: verify
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: rsk0315/oj-testcases-mirror
          token: ${{ secrets.GH_TOKEN }}
          path: oj-testcases-mirror

      - name: Prepare testcases
        run: |
          mv oj-testcases-mirror/testcases verifiers/

      - name: Verify
        run: |
          cd verifiers/verify
          cargo test --release
